set -g status-interval 60

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -s set-clipboard on
set -g mouse on
set -g allow-passthrough on

set-option -gw mode-keys vi

# 新しい window を現在の pane のディレクトリで開く
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

# keybind

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-k previous-window
bind -n M-j next-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# 下バー
set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-interval 5

## 全体背景
set -g status-style "bg=#161822,fg=#C8D0E0"

## 左側は window タブだけにする
set -g status-left ""
set -g status-left-length 0

## 右側に device 名 + session 名
set -g status-right "#[fg=#9AA4BF,bg=#1D2133] #(hostname -s)    #S "
set -g status-right-length 80

set -g window-status-separator ""

set -g window-status-format "#[fg=#9AA4BF,bg=#1D2133]   #W   "
set -g window-status-current-format "#[fg=#FFFFFF,bg=#28315B,bold]   #W   "

set -g window-status-activity-style "fg=#FFFFFF,bg=#1D2133"
set -g window-status-bell-style "fg=#FFFFFF,bg=#28315B"
